apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventory-api.fullname" . }}
  labels:
    {{- include "inventory-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.httpNodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "inventory-api.selectorLabels" . | nindent 4 }}
