language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.1.302
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
    - NODE_VERSION="10.6.0"
branches:
  only:
    - master
before_install:
  - nvm install $NODE_VERSION
before_script:
  - chmod -R a+x deploys/scripts
script:
  - ./deploys/scripts/start.sh
notifications:
  email:
    on_success: never
    on_failure: always
