# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  DOCKER_TAG: 'latest'
  DOCKER_GROUP: 'vndg'
  DOCKER_ENV: 'production'

steps:
- checkout: self
- script:
    docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
  displayName: 'docker login'
- script: |
    docker pull microsoft/dotnet:2.2.0-aspnetcore-runtime-alpine
    docker pull microsoft/dotnet:2.2.100-sdk-alpine
    docker pull nginx:alpine
    docker pull node:alpine
    docker pull mysql:8.0.12
  displayName: 'Pull Docker Images'
- script: |
    docker build -f ./deploys/dockers/mysqldb/Dockerfile -t $(DOCKER_USERNAME)/cs-mysqldb:$(DOCKER_TAG) .
    docker tag $(DOCKER_USERNAME)/cs-mysqldb:$(DOCKER_TAG) $(DOCKER_GROUP)/cs-mysqldb:$(DOCKER_TAG)
    docker push $(DOCKER_GROUP)/cs-mysqldb:$(DOCKER_TAG)
  displayName: 'Build MySQL Database'
- script: |
    docker build -f ./src/services/idp/Dockerfile -t $(DOCKER_USERNAME)/cs-idp-service:$(DOCKER_TAG) .
    docker tag $(DOCKER_USERNAME)/cs-idp-service:$(DOCKER_TAG) $(DOCKER_GROUP)/cs-idp-service:$(DOCKER_TAG)
    docker push $(DOCKER_GROUP)/cs-idp-service:$(DOCKER_TAG)
  displayName: 'Build IdP Service'
- script: |
    docker build -f ./src/services/inventory/Dockerfile -t $(DOCKER_USERNAME)/cs-inventory-service:$(DOCKER_TAG) .
    docker tag $(DOCKER_USERNAME)/cs-inventory-service:$(DOCKER_TAG) $(DOCKER_GROUP)/cs-inventory-service:$(DOCKER_TAG)
    docker push $(DOCKER_GROUP)/cs-inventory-service:$(DOCKER_TAG)
  displayName: 'Build Inventoty Service'
- script: |
    docker build -f ./src/services/catalog/Dockerfile -t $(DOCKER_USERNAME)/cs-catalog-service:$(DOCKER_TAG) .
    docker tag $(DOCKER_USERNAME)/cs-catalog-service:$(DOCKER_TAG) $(DOCKER_GROUP)/cs-catalog-service:$(DOCKER_TAG)
    docker push $(DOCKER_GROUP)/cs-catalog-service:$(DOCKER_TAG)
  displayName: 'Build Catalog Service'
- script: |
    echo "Build Rating Service"
    docker build -f ./src/services/rating/Dockerfile -t $(DOCKER_USERNAME)/cs-rating-service:$(DOCKER_TAG) .
    docker tag $(DOCKER_USERNAME)/cs-rating-service:$(DOCKER_TAG) $(DOCKER_GROUP)/cs-rating-service:$(DOCKER_TAG)
    docker push $(DOCKER_GROUP)/cs-rating-service:$(DOCKER_TAG)
  displayName: 'Build Rating Service'
- script: |
    docker build -f ./src/services/cart/Dockerfile -t $(DOCKER_USERNAME)/cs-cart-service:$(DOCKER_TAG) .
    docker tag $(DOCKER_USERNAME)/cs-cart-service:$(DOCKER_TAG) $(DOCKER_GROUP)/cs-cart-service:$(DOCKER_TAG)
    docker push $(DOCKER_GROUP)/cs-cart-service:$(DOCKER_TAG)
  displayName: 'Build Cart Service'
- script: |
    docker build -f ./src/web/Dockerfile -t $(DOCKER_USERNAME)/cs-spa:$(DOCKER_TAG) .
    docker tag $(DOCKER_USERNAME)/cs-spa:$(DOCKER_TAG) $(DOCKER_GROUP)/cs-spa:$(DOCKER_TAG)
    docker push $(DOCKER_GROUP)/cs-spa:$(DOCKER_TAG)
  displayName: 'Build Web - Vuejs'

