version: "3"
services:
  envoy-proxy:
    container_name: envoy-proxy
    image: "vndg/cs-envoy-proxy"
    restart: always
    expose:
      - "80"
      - "8081"
    ports:
      - "8082:80"
      - "8081:8081"

  open-api-service:
    container_name: open-api-service
    image: "vndg/cs-open-api"
    restart: always
    ports:
      - "5010:5010"
    expose:
      - "5010"

  mongodb:
    container_name: mongodb
    image: "bitnami/mongodb"
    restart: always
    expose:
      - "27017"
    ports:
      - "27017:27017"

  catalog-service:
    container_name: catalog-service
    image: "vndg/cs-catalog-service"
    restart: always
    environment:
      - NODE_ENV=development
      - MONGO_DB_URL=mongodb://mongodb/catalog
      - PORT=5002
    ports:
      - "5002:5002"
    expose:
      - "5002"

  cart-service:
    container_name: cart-service
    image: "vndg/cs-cart-service"
    restart: always
    ports:
      - "5003:5003"
    expose:
      - "5003"

  inventory-service:
    container_name: inventory-service
    image: "vndg/cs-inventory-service"
    restart: always
    ports:
      - "5004:5004"
    expose:
      - "5004"

  #  rating-service:
  #    container_name: rating-service
  #    image: "vndg/cs-rating-service"
  #    restart: always
  #    ports:
  #      - "5005:5005"
  #    expose:
  #      - "5005"

  review-service:
    container_name: review-service
    image: "vndg/cs-review-service"
    restart: always
    ports:
      - "5006:5006"
    expose:
      - "5006"
