hosts:
  web: coolstore.aks
  api: api.coolstore.aks
  idp: id.coolstore.aks

idpSettings:
  HostSettings__BashPath: /
  HostSettings__SwaggerRedirectUri: http://api.coolstore.aks/swagger/oauth2-redirect.html
  HostSettings__SwaggerPostLogoutRedirectUri: http://api.coolstore.aks
  HostSettings__SwaggerAllowedCorsOrigin: http://api.coolstore.aks