fullnameOverride: coolstore
image:
  repository: https://github.com/vietnam-devs/coolstore-microservices
  pullPolicy: IfNotPresent # or Always
  imageRegistry: vndg
  dockerTag: latest

nginx:
  enabled: false

hosts:
  web: coolstore.local
  api: api.coolstore.local
  idp: id.coolstore.local

gateway:
  ip: 127.0.0.1

idpSettings:
  BasePath: /
  Hosts__Externals__CurrentUri: http://id.coolstore.local/
  SwaggerRedirectUri: http://api.coolstore.local/swagger/oauth2-redirect.html
  SwaggerPostLogoutRedirectUri: http://api.coolstore.local
  SwaggerAllowedCorsOrigin: http://api.coolstore.local

catalogSettings:
  NodeEnv: "production"
  Host: "0.0.0.0"
  Port: 5002
  MongoDb:
    Host: "mymongodb.coolstore"
    Port: "27017"
    Name: "catalog"

cartSettings:
  Hosts__Local__Host: "0.0.0.0"
  Hosts__Local__Port: 5003
  Features__EfCore__MySqlDb__FQDN: "cartdb.coolstore:3306"
  Hosts__Externals__Catalog__Uri: "http://api.coolstore.local/catalog"

inventorySettings:
  Hosts__Local__Host: "0.0.0.0"
  Hosts__Local__Port: 5004
  Features__EfCore__MySqlDb__FQDN: "inventorydb.coolstore:3306"

reviewSettings:
  Hosts__Local__Host: "0.0.0.0"
  Hosts__Local__Port: 5006
  Features__Mongo__ConnString: "mongodb://mymongodb.coolstore:27017"

ratingSettings:
  NodeEnv: "production"
  Host: "0.0.0.0"
  Port: 5007
  MongoDb:
    Host: "mymongodb.coolstore"
    Port: "27017"
    Name: "rating"
    
webSettings:
  NODE_ENV: development
  NODE_WEB_ENV: http://coolstore.local/
  NODE_IDP_ENV: http://id.coolstore.local/
  NODE_CATALOG_ENV: http://api.coolstore.local/
  NODE_CART_ENV: http://api.coolstore.local/
  NODE_INVENTORY_ENV: http://api.coolstore.local/
  NODE_RATING_ENV: http://api.coolstore.local/
  NODE_IDP_HOST: id.coolstore.local