image:
  pullPolicy: Always

hosts:
  web: cool-store.ml
  api: api.cool-store.ml
  idp: id.cool-store.ml

idpSettings:
  BashPath: /
  ExternalCurrentUri: http://id.cool-store.ml/
  SwaggerRedirectUri: http://api.cool-store.ml/swagger/oauth2-redirect.html
  SwaggerPostLogoutRedirectUri: http://api.cool-store.ml
  SwaggerAllowedCorsOrigin: http://api.cool-store.ml
  SpaAllowedCorsOrigin: http://cool-store.ml

cartSettings:
  CatalogUri: "http://api.cool-store.ml/catalog"
  MySqlDbFQDN: "13.66.62.124:3306"
  MySqlDbUserName: "dbuser@mysqldblab01"

inventorySettings:
  MySqlDbFQDN: "13.66.62.124:3306"
  MySqlDbUserName: "dbuser@mysqldblab01"

spaSettings:
  NodeEnv: development
  WebUri: http://cool-store.ml/
  IdpUri: http://id.cool-store.ml/
  OpenApiUri: http://api.cool-store.ml/

openAPISettings:
  CatalogEndPoint: catalog:5002
  CartEndPoint: cart:5003
  InventoryEndPoint: inventory:5004
  RatingEndPoint: rating:5007
