apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cart-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        transcode: http
        app: cart
        version: v1
    spec:
      containers:
      - name: cart
        image: {{.Values.image.imageRegistry}}/cs-cart-service:{{.Values.image.dockerTag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: Hosts__Local__Host
          value: {{ .Values.cartSettings.Hosts__Local__Host }}
        - name: Hosts__Local__Port
          value: {{ .Values.cartSettings.Hosts__Local__Port | quote }}
        - name: Hosts__Externals__Catalog__Uri
          value: {{ .Values.cartSettings.Hosts__Externals__Catalog__Uri }}
        - name: Features__EfCore__MySqlDb__FQDN
          value: {{ .Values.cartSettings.Features__EfCore__MySqlDb__FQDN }}
        - name: Features__EfCore__MySqlDb__Password
          valueFrom:
            secretKeyRef:
              name: cart-secrets
              key: MySqlDbPassword
        ports:
        - containerPort: {{ .Values.cartSettings.Hosts__Local__Port }}
        readinessProbe:
          initialDelaySeconds: 15
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5003"]
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:5003"]
        resources:
          requests:
            memory: "300Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "100m"
---
