apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cartdb-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cartdb
        version: v1
    spec:
      containers:
      - name: cartdb
        image: {{.Values.image.imageRegistry}}/cs-mysqldb:{{.Values.image.dockerTag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "P@ssw0rd"
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: "1G"
            cpu: "200m"
          limits:
            memory: "1G"
            cpu: "200m"
---
