{{- if ne .Values.nginx.enabled true -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cs-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.hosts.web }}
    - {{ .Values.hosts.api }}
    - {{ .Values.hosts.idp }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-vs
spec:
  hosts:
  - {{ .Values.hosts.web }}
  gateways:
  - cs-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: spa-service
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: id-vs
spec:
  hosts:
  - {{ .Values.hosts.idp }}
  gateways:
  - cs-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: idp-service
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: inv-vs
spec:
  hosts:
  - {{ .Values.hosts.api }}
  gateways:
  - cs-gateway
  http:
  - match:
    - uri:
        prefix: /gw/
    route:
    - destination:
        host: gateway-service
        port:
          number: 80
  - match:
    - uri:
        prefix: /inv/
    route:
    - destination:
        host: inventory-service
        port:
          number: 80
  - match:
    - uri:
        prefix: /cat/
    route:
    - destination:
        host: catalog-service
        port:
          number: 80
  - match:
    - uri:
        prefix: /cart/
    route:
    - destination:
        host: cart-service
        port:
          number: 80
{{- end -}}
