{{- if ne .Values.nginx.enabled true -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cs-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.hosts.web }}
    - {{ .Values.hosts.api }}
    - {{ .Values.hosts.idp }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-vs
spec:
  hosts:
  - {{ .Values.hosts.web }}
  gateways:
  - cs-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: spa-service
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: id-vs
spec:
  hosts:
  - {{ .Values.hosts.idp }}
  gateways:
  - cs-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: idp-service
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: api-vs
spec:
  hosts:
  - {{ .Values.hosts.api }}
  gateways:
  - cs-gateway
  http:
  - match:
    - uri:
        prefix: /inventory/
    route:
    - destination:
        host: inventory-service
        port:
          number: 80
  - match:
    - uri:
        prefix: /catalog/
    route:
    - destination:
        host: catalog-service
        port:
          number: 80
  - match:
    - uri:
        prefix: /rating/
    route:
    - destination:
        host: rating-service
        port:
          number: 80
  - match:
    - uri:
        prefix: /cart/
    route:
    - destination:
        host: cart-service
        port:
          number: 80
  - match:
    - uri:
        prefix: /review/
    route:
    - destination:
        host: review-service
        port:
          number: 80
---	
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-id
spec:
  hosts:
  - id.coolstore.local
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: example-http
    protocol: HTTP
  resolution: DNS
---	
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-api
spec:
  hosts:
  - api.coolstore.local
  location: MESH_EXTERNAL
  ports:
  - number: 80
    name: example-http
    protocol: HTTP
  resolution: DNS
{{- end -}}
