apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: idp-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: idp
        version: v1
    spec:
      containers:
      - name: idp
        image: {{.Values.image.imageRegistry}}/cs-idp-service:{{.Values.image.dockerTag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: HostSettings__BasePath
          value: {{ .Values.idpSettings.BasePath }}
        - name: Hosts__Externals__CurrentUri
          value: {{ .Values.idpSettings.Hosts__Externals__CurrentUri }}
        - name: HostSettings__SwaggerRedirectUri
          value: {{ .Values.idpSettings.SwaggerRedirectUri }}
        - name: HostSettings__SwaggerPostLogoutRedirectUri
          value: {{ .Values.idpSettings.SwaggerPostLogoutRedirectUri }}
        - name: HostSettings__SwaggerAllowedCorsOrigin
          value: {{ .Values.idpSettings.SwaggerAllowedCorsOrigin }}
        - name: HostSettings__SpaAllowedCorsOrigin
          value: {{ .Values.idpSettings.SpaAllowedCorsOrigin }}
        ports:
        - name: http
          containerPort: 5001
        resources:
          requests:
            memory: "1G"
            cpu: "100m"
          limits:
            memory: "1G"
            cpu: "100m"
---
