apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviewdb-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviewdb
        version: v1
    spec:
      containers:
      - name: reviewdb
        image: {{.Values.image.imageRegistry}}/cs-mysqldb:{{.Values.image.dockerTag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "P@ssw0rd"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD 
          value: false
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: false
        - name: DB_TYPE
          value: "mysql"
        - name: MYSQL_DB_HOST
          value: "maindb"
        - name: MYSQL_DB_PORT
          value: "3306"
        - name: MYSQL_DB_USER
          value: "root"
        - name: MYSQL_DB_PASSWORD
          value: "P@ssw0rd"
        ports:
        - containerPort: 3306
---
