apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviewdb-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviewdb
        version: v1
    spec:
      containers:
      - name: reviewdb
        image: {{.Values.image.imageRegistry}}/cs-mysqldb:{{.Values.image.dockerTag}}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "P@ssw0rd"
        ports:
        - containerPort: 3306
---
