# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  vmImage: "Ubuntu 16.04"

variables:
  DOCKER_TAG: "latest"
  DOCKER_GROUP: "vndg"
  DOCKER_ENV: "production"

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/services/idp/*

steps:
  - checkout: self
  - script: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
    displayName: "docker login"
  - script: |
      docker pull microsoft/dotnet:2.2.100-sdk-alpine
      docker pull microsoft/dotnet:2.2.0-aspnetcore-runtime-alpine
    displayName: "Pull Docker Images"
  - script: |
      docker build -f ./src/services/idp/Dockerfile -t $(DOCKER_USERNAME)/cs-idp-service:$(DOCKER_TAG) .
      docker tag $(DOCKER_USERNAME)/cs-idp-service:$(DOCKER_TAG) $(DOCKER_GROUP)/cs-idp-service:$(DOCKER_TAG)
      docker push $(DOCKER_GROUP)/cs-idp-service:$(DOCKER_TAG)
    displayName: "Build IdP Service"
