##################################################################################################
# Idp configuration
##################################################################################################

#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: tcp-configmap-idp-service
#data:
#  5001: "default/idp-service:5001"
#---
apiVersion: v1
kind: Service
metadata:
  name: idp-service
  labels:
    app: idp-service
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 32766
    targetPort: 5000
    protocol: TCP
    name: http
  - port: 5001
    nodePort: 32767
    targetPort: 5001
    protocol: TCP
    name: https
  selector:
    app: idp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: idp-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: idp
        version: v1
    spec:
      containers:
      - name: idp
        image: vietnamdevsgroup/coolstore-idp-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: "ASPNETCORE_BASEPATH"
          value: "/idp/"
        ports:
        - name: http
          containerPort: 5000
        - name: https
          containerPort: 5001
---
