# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  vmImage: "Ubuntu 16.04"

variables:
  DOCKER_TAG: "latest"
  DOCKER_GROUP: "vndg"
  DOCKER_ENV: "production"

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/services/rating/*

steps:
  - checkout: self
  - script: docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
    displayName: "docker login"
  - script: |
      docker pull node:alpine
    displayName: "Pull Docker Images"
  - script: |
      echo "Build Rating Service"
      docker build -f ./src/services/rating/Dockerfile -t $(DOCKER_USERNAME)/cs-rating-service:$(DOCKER_TAG) .
      docker tag $(DOCKER_USERNAME)/cs-rating-service:$(DOCKER_TAG) $(DOCKER_GROUP)/cs-rating-service:$(DOCKER_TAG)
      docker push $(DOCKER_GROUP)/cs-rating-service:$(DOCKER_TAG)
    displayName: "Build Rating Service"
