apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog
        version: v1
    spec:
      containers:
      - name: catalog
        image: vndg/cs-catalog-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: "MONGO_DB_URL"
          value: "mongodb://mongodb:27017/catalog"
        ports:
        - containerPort: 5002
---
