apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
        version: v1
    spec:
      containers:
      - name: gateway
        image: vietnamdevsgroup/coolstore-gateway-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: "ASPNETCORE_BASEPATH"
          value: "/cs/"
        - name: "DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER"
          value: "1"
        - name: "HostSettings__CurrentHostUri"
          value: {{ .Values.gatewaySettings.HostSettings__CurrentHostUri }}
        - name: "HostSettings__AuthorityHostUri"
          value: {{ .Values.gatewaySettings.HostSettings__AuthorityHostUri }}
        ports:
        - containerPort: 5000
---
