apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
        version: v1
    spec:
      containers:
      - name: gateway
        image: vietnamdevsgroup/coolstore-gateway-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: "HostSettings__AspNetCoreBasePath"
          value: {{ .Values.gatewaySettings.HostSettings__AspNetCoreBasePath | quote }}
        - name: "HostSettings__CurrentHostUri"
          value: {{ .Values.gatewaySettings.HostSettings__CurrentHostUri | quote }}
        - name: "HostSettings__AuthorityHostUri"
          value: {{ .Values.gatewaySettings.HostSettings__AuthorityHostUri | quote }}
        ports:
        - containerPort: 5000
---
