apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: idp-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: idp
        version: v1
    spec:
      containers:
      - name: idp
        image: vndg/cs-idp-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: "ASPNETCORE_BASEPATH"
          value: "/"
        - name: "HostSettings__SwaggerRedirectUri"
          value: {{ .Values.idpSettings.HostSettings__SwaggerRedirectUri }}
        - name: "HostSettings__SwaggerPostLogoutRedirectUri"
          value: {{ .Values.idpSettings.HostSettings__SwaggerPostLogoutRedirectUri }}
        - name: "HostSettings__SwaggerAllowedCorsOrigin"
          value: {{ .Values.idpSettings.HostSettings__SwaggerAllowedCorsOrigin }}
        ports:
        - name: http
          containerPort: 5001
---
