apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: idp-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: idp
        version: v1
    spec:
      containers:
      - name: idp
        image: vietnamdevsgroup/coolstore-idp-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: "ASPNETCORE_BASEPATH"
          value: "/idp/"
        - name: "HostSettings__SwaggerRedirectUri"
          value: {{ .Values.idpSettings.HostSettings__SwaggerRedirectUri | quote }}
        - name: "HostSettings__SwaggerPostLogoutRedirectUri"
          value: {{ .Values.idpSettings.HostSettings__SwaggerPostLogoutRedirectUri | quote }}
        - name: "HostSettings__SwaggerAllowedCorsOrigin"
          value: {{ .Values.idpSettings.HostSettings__SwaggerAllowedCorsOrigin | quote }}
        ports:
        - name: http
          containerPort: 5000
---
