apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inventory-v1
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory
        version: v1
    spec:
      containers:
      - name: inventory
        image: vietnamdevsgroup/coolstore-inventory-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: "ASPNETCORE_BASEPATH"
          value: "/inventory/"
        - name: "CURRENT_HOST_URI"
          value: "https://192.168.1.5:8443/inventory"
        - name: "AUTHORITY_HOST_URI"
          value: "https://192.168.1.5:8443/idp"
        ports:
        - containerPort: 5000
---
