apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: coolstore-ingress
  namespace: default
spec:
  rules:
  - host: idp.coolstore.local
    http:
      paths:
      - path: /
        backend:
          serviceName: idp-service
          servicePort: 5000
  - host: coolstore.local
    http:
      paths:
      - path: /
        backend:
          serviceName: spa-service
          servicePort: 8080
      - path: /cs
        backend:
          serviceName: gateway-service
          servicePort: 5000
